### ISSUE TITLE
`true` is not defined when running demo.ipynb

### ISSUE THREAD

**Issue by froggomad** [microsoft/i-Code#80]
After following the installation instructions and trying to run the demo notebook, I get a fatal error indicating `true` was used instead of `True` in `runpy.py`

> ←[1;31mNameError←[0m: name 'true' is not definedTraceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\CoDi\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\envs\CoDi\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\CoDi\Scripts\jupyter-run.EXE\__main__.py", line 7, in <module>
  File "C:\ProgramData\Anaconda3\envs\CoDi\lib\site-packages\jupyter_core\application.py", line 285, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\CoDi\lib\site-packages\traitlets\config\application.py", line 1043, in launch_instance
    app.start()
  File "C:\ProgramData\Anaconda3\envs\CoDi\lib\site-packages\jupyter_client\runapp.py", line 112, in start
    raise Exception("jupyter-run error running '%s'" % filename)
Exception: jupyter-run error running 'demo.ipynb'
[IPKernelApp] WARNING | Parent appears to have exited, shutting down.

**Comment by froggomad** [comment]
Issue is with the jupyter installation as I'm able to run the notebook in a GUI client
